backend:
  name: github
  repo: dlrkdxor0821/dlrkdxor0821.github.io
  branch: main
  base_url: https://decap-cms-oauth-worker.leekt.workers.dev
  auth_endpoint: /auth

media_folder: site/public/uploads
public_folder: /uploads

collections:
  - name: posts
    label: 개발 일지
    folder: site/content
    create: true
    slug: '{{fields.date}}-{{slug}}'
    fields:
      - { label: 제목, name: title, widget: string }
      - { label: 날짜, name: date, widget: datetime, format: 'YYYY-MM-DD', date_format: 'YYYY-MM-DD', time_format: false }
      - { label: 프로젝트, name: project, widget: string, default: 기타 }
      - { label: 태그, name: tags, widget: list, default: [] }
      - { label: 본문, name: body, widget: markdown }
